### ISSUE TITLE
release day checklist - things needed to pass to release token migration

### ISSUE THREAD

**Issue by sadiqevani** [aeternity/aepp-token-migration#14]
- [x] Users should be able to close the QR Code scanner and end up in /migration
- [x] Web3 gets instantiated multiple times. FIX IT!
- [x] Notifications pages (blocking, non blocking)
- [x] Address spacing / structure fix
- [x] Standalone Payload function 
- [x] Detection for the right network with Metamask (blocker)
- [x] If people don't AE and ETH, notify / block
- [x] print function for the transaction page
  - [x] use the print function from the chrome
- [x] Improve Account Dispplay in the upper right corner 
  - [x] ( 2 chunks of three ... 2 chunks of three)
  - [x] Copy Address to clipboard if users click on ...
- [x] Check AEternity address for base58 checksum
- [x] refactoring :P
- [x] Ledger wallet works only for Chrome, show blocking notifications when its another browser.
  - [x] allow chrome, brave browser (or chrome related browsers)
- [x] With Ledger wallet, first get the address without verification, and load it on the screen, and when the user wants to proceed on the next page, use the `verify: true` argument so the user can verify this address from the ledger hardware
- [x] Create a `prod` and `dev` environment with all sensitive variables / global ones
- [x] Add a modal after the user tries to migrate with MyEtherWallet, that has two buttons to "check transaction" and "Migrate Step"
- [x] Split home page from main app 
- [x] User ledger button colors from the design
  - [ ] Update the code for a more scalable solution
- [ ] single transaction page (low priority)
- [ ] Unsuccessful transactions still go through (in the result page, and display error)
- [ ] wording and style fixes (high priority)
  - [ ] wording
  - [x] styles
- [x] separate payload verification
- [ ] responsive designs
- [ ] we need a setup so we can disable Ledger Wallet pages / sections / buttons
- [ ] reduce file / page size - bundle it into a single html side
- [x] fix sliders design
- [ ] Replace the link in the first page with the blogpost about how to migrate tokens (blogpost)
